config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/kalininalab/alphafold_non_docker:
      branch: main
      repo: https://github.com/kalininalab/alphafold_non_docker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/kalininalab/alphafold_non_docker git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-chartreuse-spaniel.sh
        container: qc.acc_tasty-violet-sponge
  QC.Doc:
    repos:
      github.com/kalininalab/alphafold_non_docker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-persimmon-crab.sh
        container: qc.doc_randy-pink-uakari
      github.com/kalininalab/alphafold_non_docker git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-heliotrope-squid.sh
        container: qc.doc_craggy-ivory-sparrow
      github.com/kalininalab/alphafold_non_docker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-amaranth-sponge.sh
        container: qc.doc_nippy-brass-angelfish
  QC.Lic:
    repos:
      github.com/kalininalab/alphafold_non_docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-russet-newfoundland.sh
        container: qc.lic_lumpy-salmon-octopus
  QC.Sty:
    repos:
      github.com/kalininalab/alphafold_non_docker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-thistle-fowl.sh
        container: qc.sty_surly-platinum-penguin
  QC.Ver:
    repos:
      github.com/kalininalab/alphafold_non_docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-champagne-lion.sh
        container: qc.ver_zippy-blue-javanese
timeout: 5400
